# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
#    -   id: trailing-whitespace
#    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: ssh://git.hq.audiokinetic.com:29418/PreCommit/Unreal
    rev: v1.0.0
    hooks:
    -   id: unreal-version-checker
        args: [--maxversion=5.1.1]
-   repo: ssh://git.hq.audiokinetic.com:29418/PreCommit/Wwise
    rev: v1.0.0
    hooks:
    -   id: wwise-license-checker
